[formatting]
align_entries    = false
crlf             = false
reorder_keys     = false
trailing_newline = true

exclude = ["Cargo.lock"]

[[rule]]
include = ["**/Cargo.toml"]
keys    = ["dependencies", "dev-dependencies", "build-dependencies"]

[rule.formatting]
reorder_keys = true

[[rule]]
include = ["*rustfmt.toml", "*taplo.toml"]

[rule.formatting]
align_entries = true
reorder_keys  = true
